### ISSUE TITLE
Docker container fails to start with version 1.0.2

### ISSUE THREAD

**Issue by Sebalextoel** [Cuupa/classificator#12]
After updating to 1.0.2, the docker Container fails to start.
-replacing app-1.0.0.jar with app-1.0.2.jar
-replacing kb-1.0.0.db with kb-1.0.1.kb
-adjusting mounting pathways
The issue persists with a freshly created Container.

COntainer: OpenJDK
Java Version: 15.0.2

Docker Logs:
 [main] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
Failed to bind properties under 'logging.level.com.cuupa.classificator' to org.springframework.boot.logging.LogLevel:
    Property: logging.level.com.cuupa.classificator
    Value: WARNING
    Origin: class path resource [application.yml] from app.jar - 8:28
    Reason: failed to convert java.lang.String to org.springframework.boot.logging.LogLevel
Action:
Update your application's configuration. The following values are valid:
    DEBUG
    ERROR
    FATAL
    INFO
    OFF
    TRACE
    WARN

**Comment by Cuupa** [comment]
Fixed with Version 1.0.3
